package dev.lbuddyboy.lmotd.util;

import java.util.Arrays;
import java.util.List;

public class NameUtils {

    public static List<String> NAMES = Arrays.asList(
            "HealerRole"
            , "Astericc"
            , "BugNumero"
            , "Chromedx"
            , "Chronosco"
            , "JuZzSpot"
            , "Phiapht"
            , "Prouder"
            , "Santagal"
            , "Scapuls"
            , "SincereHeadlines"
            , "Solider"
            , "BZzZzZzy"
            , "IWannaHacj"
            , "Partype"
            , "Stabber"
            , "RebelBabe"
            , "Crusher"
            , "Comfywi"
            , "Confler"
            , "FinestSolid"
            , "Digestey"
            , "Gurlyus"
            , "HyperFlea"
            , "ReporterFox"
            , "Reportski"
            , "Snowboardor"
            , "Thereat"
            , "Thrillaww"
            , "TwitScan"
            , "VivalaQuick"
            , "VulturePerfect"
            , "ChooseBreaking"
            , "Shayters"
            , "SimonCoverage"
            , "Sombererta"
            , "Obliterator"
            , "IssueCy"
            , "KurisuInvent"
            , "Leistorks"
            , "LoverLocal"
            , "Networen"
            , "Nice1Too"
            , "RelyHot"
            , "Hitter69"
            , "Exoticempt"
            , "Farerge"
            , "Conqueris"
            , "JungWalker"
            , "FriedBee"
            , "BossFireball"
            , "CartridgeZine"
            , "Glimmette"
            , "InsiderTrevor"
            , "Clencher"
            , "Piertuck"
            , "ShadowReptile"
            , "grifツ"
            , "Mortal Llama"
            , "FrostFull"
            , "Boss69up"
            , "D4Destroyer"
            , "Hell Raiser"
            , "Invictus"
            , "Never Genesis"
            , "Holly Secret"
            , "Spellbinder"
            , "Kabookie"
            , "HanCampaign"
            , "ChilledCoop"
            , "Criminology"
            , "Columnalet"
            , "DramaPlace"
            , "Evenbull"
            , "MutantBoy"
            , "Teen Outlaws"
            , "The Blank Pain"
            , "Fallen Five"
            , "First Reign"
            , "Midnight Power"
            , "Exterminator"
            , "Thrashers"
            , "RespectMeBitch"
            , "Checkpoint1"
            , "Crimeter"
            , "Defendakey"
            , "Delightvi"
            , "Wreckers"
            , "SlammerHam"
            , "VanixX"
    );

}
