redis: # Please note you still need redis if you want network syncing
  use: true
  local:
    host: "localhost"
    port: 6379
    auth:
      enabled: false
      password: ""
    channel-id: 0
  backend:
    host: "localhost"
    port: 6379
    auth:
      enabled: false
      password: ""
    channel-id: 0
